### ISSUE TITLE
No attribute for any function in mimicpy ? 

### ISSUE THREAD

**Issue by qduez** [bharurn/mimicpy#30]
Hello, 

I am trying to use mimicpy to run QMMM simulations with Gromacs and CPMD. I downloaded the mimicpy repository on my Linux machine as suggested in the README file. After that, I opened Python 3.7.4, added the folder of mimicpy using the sys package, as suggested in the README file. At that point, I can import mimicpy without any problem.

However, when I try call any function, like getHost or Prepare, I always get an error saying that 'mimicpy' has no attribute 'function'. If I use dir(mimicpy), here is the output:

>>> dir(mimicpy)
['__authors__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_authors', '_version', 'logging']

Am I doing something wrong ? Can you please tell me how I can correctly use mimicpy ? 

Thanks a lot !

**Comment by bharurn** [comment]
Hello,

Thank you for your interest in MiMiCPy. Here are a couple of things to keep in mind while using this package:

1) MiMiCPy is the input script preparation toolset for MiMiC. MiMiC is an improvement to the current QM/MM code of CPMD, and interfaces with Gromacs, and is developed at our group. Refer to [this]( https://pubs.acs.org/doi/abs/10.1021/acs.jctc.9b00093) and [this]( http://manual.gromacs.org/documentation/2019-rc1/reference-manual/special/mimic-qmmm.html) for more info. It requires special versions of Gromacs and CPMD to be compiled from source. Since the code is not yet production ready, it has not been made public yet. But it will be soon! You can look for it in the official [Gitlab repo](https://gitlab.com/MiMiC-projects) (MiMiCPy will also soon be moved there too).

2) We recently applied major changes to MiMiCPy, but we have yet to update the documentation. A lot of the features were forked into another library called [wf4gmx]( https://github.com/bharurn/wf4gmx). These mostly include the pythonic workflow to prepare, run and analyse pure Gromacs MD and MiMiC QM/MM simulations. This leaves only the MiMiC input preparation script functionality in MiMiCPy. A lot of the functionalities you mentioned like getHost(), etc. have moved to wf4gmx. So, you might want to take a look at that repo. However, this is also in the early stages of development and documentation is scarce at the moment.

If you have any more questions, esp. with regards to running a full QM/MM or MD simulation through a python workflow, I suggest you post an issue on the wf4gmx repo. I am closing this issue for now.

Thanks,
Bharath
